name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  markdown_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Markdown file
        # uses: docker://avtodev/markdown-lint:v1
        uses: avto-dev/markdown-lint@v1
        with:
          args: "."
